---
- name: Configure DNF Automatic Services
  hosts: "{{ host_list }}"
  gather_facts: false
  become: true
  vars:
    Download_Time: 'OnCalendar=*-*-* 16:00' # you must follow the format

  tasks:

    - name: Run a command to refresh the subscription-manager to update the errate in satellite
      loop:
        - subscription-manager config --rhsm.package_profile_on_trans 1
        - subscription-manager refresh
      changed_when: "result_subscription_manager.rc == 1"
      failed_when: "result_subscription_manager.rc > 1"
      register: "result_subscription_manager"
      command: "{{ item }}"

    - name: update the packages dnf-automatic-download package
      vars:
        packages:
        - dnf-automatic
      ignore_errors: true
      yum:
        name: "{{ packages }}"
        state: latest

    - name: Enable the the service dnf-automatic
      with_items:
        - dnf-automatic.timer
        - dnf-automatic-notifyonly.timer
        - dnf-automatic-download.timer
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
        
    - name: Update the time in the dnf-automatic-download.timer service
      notify:
        - Reload systemd daemon
        - Restart dnf-automatic-download.timer
      lineinfile:
        path: /usr/lib/systemd/system/dnf-automatic-download.timer
        regexp: '^OnCalendar='
        line: "{{ Download_Time }}"

  handlers:

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Restart dnf-automatic-download.timer
      service:
        name: dnf-automatic-download.timer
        state: restarted

    - name: Restart dnf-automatic-notifyonly.timer
      service:
        name: dnf-automatic-notifyonly.timer
        state: restarted
