---
- name: Enable specific repositories and disable the other
  hosts: localhost
  vars:
    enable_repos:
      - rhel-9-for-x86_64-appstream-rpms
      - rhel-9-for-x86_64-baseos-rpms
      - ansible-automation-platform-2.4-for-rhel-9-x86_64-rpms
  tasks:
    - name: Disable all repositories except rhel-7-server-rpms
      community.general.rhsm_repository:
        name: "{{ enable_repos }}" 
        purge: true
